// Generated by CoffeeScript 1.8.0
var Data, model;

Data = (function() {
  function Data(opts) {
    var id, opt, res, _i, _len;
    if (this.is(opts, 'Array')) {
      res = {};
      id = 0;
      for (_i = 0, _len = opts.length; _i < _len; _i++) {
        opt = opts[_i];
        if (!opt.id) {
          opt.id = id++;
        }
        res[opt.id] = opt;
      }
      this.data = res;
    } else {
      this.data = {};
      id = opts && opts.id ? opts.id : '1';
      this.data[id] = opts;
    }
  }

  Data.prototype.is = function(v, type) {
    return toString.apply(v) === ("[object " + type + "]");
  };

  Data.prototype.get = function(key) {
    if (this.size() > 1) {
      return new Data(this.data[key]);
    }
    return this.json()[key];
  };

  Data.prototype.size = function() {
    var c, i;
    c = 0;
    for (i in this.data) {
      c++;
    }
    return c;
  };

  Data.prototype.json = function() {
    var i, res;
    res = [];
    for (i in this.data) {
      if (this.size() === 1) {
        return this.data[i];
      }
      res.push(this.data[i]);
    }
    return res;
  };

  return Data;

})();

model = new Data([
  {
    id: '1',
    age: 12
  }, {
    id: 'w',
    age: 10
  }
]);
