// Generated by CoffeeScript 1.8.0
var tag;

tag = '<h3>{title}</h3> <ul> <li each="{items}"> <label class="{completed: done}"></label> <input type="checkbox" __checked="{done}" onclick="{parent.toggle}"> <span onclick="{parent.edited}" style="display: {!edited}">{title}</span> <input value="{title}" onenter="{parent.update}" type="{hidden: !edited}"/> </li> </ul> <form onsubmit="{add}"> <input name="input" onkeyup="{edit}"> <button __disabled="{!text}">Add {items.length + 1}</button> </form>';

riot.tag('todo', tag, function(opts) {
  this.disabled = true;
  this.items = opts.items || [];
  this.title = opts.title;
  this.add = function(e) {
    if (!this.text) {
      return;
    }
    this.items.push({
      title: this.text,
      edited: false
    });
    return this.text = this.input.value = "";
  };
  this.edit = function(e) {
    return this.text = e.target.value;
  };
  this.edited = function(e, a) {
    return console.log(e, a, 111);
  };
  this.update = function(e, a) {
    return console.log(e, a, 222);
  };
  return this.toggle = function(e) {
    e.item.done = !e.item.done;
    return true;
  };
});
