// Generated by CoffeeScript 1.9.1
var application;

C.Application = application = (function() {
  function application(options) {
    this.options = options != null ? options : {};
    this.urlRoot = this.options.urlRoot || '';
    this.contentType = this.options.contentType || 'application/x-www-form-urlencoded';
    this.router = new C.Router(this.options.router);
    riot.observable(this);
  }

  application.prototype.start = function() {
    this.container = this.mount(this.options.container);
    return this.router.start();
  };

  application.prototype.mount = function(tagName) {
    var tag;
    this.tags = this.tags || {};
    tag = riot.mount(tagName)[0];
    this.tags[tagName] = tag;
    this.currentTag = tag;
    return tag;
  };

  application.prototype.mixin = function(tag, obj) {
    var fn, init, item, opt;
    init = function() {};
    if (obj.events) {
      init = obj.events.init || function() {};
      fn = function(item) {
        return tag.on(item, obj.events[item]);
      };
      for (item in obj.events) {
        fn(item);
      }
    }
    if (obj.actions) {
      obj.actions.init = init;
      tag.mixin(obj.actions);
    }
    if (obj.store) {
      opt = {};
      if (C.isString(obj.store)) {
        opt.url = obj.store;
      } else if (C.isObject(obj.store)) {
        opt = obj.store;
      }
      return tag.store = new Store(app, tag, opt);
    }
  };

  return application;

})();
