// Generated by CoffeeScript 1.9.1
var Router, escapeRegExp, extractParams, namedParam, optionalParam, routeToRegExp, router, splatParam,
  slice = [].slice;

optionalParam = /\((.*?)\)/g;

namedParam = /(\(\?)?:\w+/g;

splatParam = /\*\w+/g;

escapeRegExp = /[\-{}\[\]+?.,\\\^$|#\s]/g;

routeToRegExp = function(route) {
  route = route.replace(escapeRegExp, '\\$&').replace(optionalParam, '(?:$1)?').replace(namedParam, function(match, optional) {
    if (optional) {
      return match;
    } else {
      return '([^/?]+)';
    }
  }).replace(splatParam, '([^?]*?)');
  return new RegExp('^' + route + '(?:\\?([\\s\\S]*))?$');
};

extractParams = function(route, fragment) {
  var i, len, p, params, results;
  params = route.exec(fragment).slice(1);
  results = [];
  for (i = 0, len = params.length; i < len; i++) {
    p = params[i];
    results.push(decodeURIComponent(p) || null);
  }
  return results;
};

router = function(router, args) {
  var opts, path, r, ref, results, route, routes;
  opts = router.opts;
  routes = opts.routes;
  path = args.join('/');
  results = [];
  for (r in routes) {
    route = routeToRegExp(r);
    if (!route.test(path)) {
      continue;
    }
    if (C.isFunction(routes[r])) {
      results.push(routes[r].apply(router, extractParams(route, path)));
    } else {
      results.push((ref = opts[routes[r]]) != null ? ref.apply(router, extractParams(route, path)) : void 0);
    }
  }
  return results;
};

C.Router = Router = (function() {
  function Router(opts1) {
    this.opts = opts1;
  }

  Router.prototype.start = function() {
    riot.route.exec((function(_this) {
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return router(_this, args);
      };
    })(this));
    riot.route((function(_this) {
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return router(_this, args);
      };
    })(this));
    return riot.route.start();
  };

  Router.prototype.stop = function() {
    return riot.route.stop();
  };

  Router.prototype.go = function(hash) {
    return riot.route(hash);
  };

  Router.prototype.back = function() {
    return history.back();
  };

  Router.prototype.add = function(route, fn) {
    return this.opts.routes[route] = fn;
  };

  Router.prototype.remove = function(route) {
    return delete this.opts.routes[route];
  };

  return Router;

})();
