// Generated by CoffeeScript 1.9.1
var Store;

C.Store = Store = (function() {
  function Store(app, tag, options) {
    this.app = app;
    this.tag = tag;
    this.options = options;
    this.url = this.options.url;
    this.data = this.options.data || {};
    this.params = this.options.params || {};
    delete this.options.url;
    delete this.options.data;
    delete this.options.params;
  }

  Store.prototype.get = function(data) {
    if (data == null) {
      data = {};
    }
    return this.ajax({
      type: 'GET',
      url: (data.id ? this.url + '/' + data.id : this.url)
    }, data, 'geted');
  };

  Store.prototype.post = function(data) {
    if (data == null) {
      data = {};
    }
    return this.ajax({
      type: 'POST',
      url: this.url
    }, data, 'posted');
  };

  Store.prototype.put = function(data) {
    if (data == null) {
      data = {};
    }
    return this.ajax({
      type: 'PUT',
      url: this.url + '/' + data.id
    }, data, 'puted');
  };

  Store.prototype.del = function(data) {
    if (data == null) {
      data = {};
    }
    return this.ajax({
      type: 'DELETE',
      url: this.url + '/' + data.id
    }, data, 'deleted');
  };

  Store.prototype.save = function(data) {
    if (data == null) {
      data = {};
    }
    if (data.id) {
      return this.put(data);
    } else {
      return this.post(data);
    }
  };

  Store.prototype.ajax = function(opts, data, evt) {
    var appendUrl, config, p, self;
    self = this;
    opts.contentType = this.app.contentType;
    config = C.extend(opts, this.options);
    config.url = this.app.urlRoot + config.url;
    appendUrl = '';
    for (p in this.params) {
      appendUrl += p + '=' + this.params[p] + '&';
    }
    if (appendUrl !== '') {
      config.url += '?' + appendUrl.substring(0, appendUrl.length - 1);
    }
    config.data = data;
    this.app.trigger('ajax', config);
    p = new C.Adapter.Promise();
    C.Adapter.ajax(config).done(function(resp) {
      if (evt === 'geted') {
        self.set(resp);
      }
      self.tag.trigger(evt, resp, 'success');
      if (evt === 'posted' || evt === 'puted') {
        self.tag.trigger('saved', resp, 'success');
      }
      self.app.trigger('ajaxed', resp, 'success');
      return p.resolve(resp);
    }).fail(function(resp) {
      self.tag.trigger(evt, resp, 'error');
      if (evt === 'posted' || evt === 'puted') {
        self.tag.trigger('saved', resp, 'error');
      }
      self.app.trigger('ajaxed', resp, 'error');
      return p.reject(resp);
    });
    return p.promise();
  };

  Store.prototype.set = function(d) {
    this.data = this.options.root ? d[this.options.root] : d;
    return this;
  };

  Store.prototype.clear = function() {
    this.data = {};
    return this;
  };

  return Store;

})();
